language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 30
    random_seed: 42
  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.1
policies:
  - name: RulePolicy
